"""Word generation: DDIM sampling with CFG, best-of-N, chunking, stitching, postprocessing.

Implements all five gray-box defense layers in postprocessing.
"""

import warnings

import numpy as np
import torch

warnings.filterwarnings("ignore", message=".*model-agnostic default.*max_length.*")
import torch.nn.functional as F

from reforge.config import (
    BACKGROUND_PERCENTILE,
    BODY_ZONE_BOTTOM,
    BODY_ZONE_INK_THRESHOLD,
    BODY_ZONE_TOP,
    CC_BOUNDARY_BONUS,
    CLUSTER_GAP_PX,
    COMPOSITOR_INK_THRESHOLD,
    CONSONANT_PENALTY,
    CV_BOUNDARY_BONUS,
    DEFAULT_CANVAS_HEIGHT,
    DEFAULT_CANVAS_WIDTH,
    DEFAULT_DDIM_STEPS,
    DEFAULT_GUIDANCE_SCALE,
    DEFAULT_NUM_CANDIDATES,
    HALO_DILATE_RADIUS,
    HALO_GRAY_THRESHOLD,
    INK_THRESHOLD_RATIO,
    MAX_CANVAS_WIDTH,
    MAX_WORD_LENGTH,
    MIN_CHUNK_CHARS,
    OCR_SELECTION_WEIGHT,
    STITCH_OVERLAP_PX,
    VAE_SCALE_FACTOR,
    WIDTH_MULTIPLE,
)

VOWELS = set("aeiouAEIOU")
CONSONANTS = set("bcdfghjklmnpqrstvwxyzBCDFGHJKLMNPQRSTVWXYZ")


# --- Contraction splitting ---

def is_contraction(word: str) -> bool:
    """Check if a word is a contraction containing an apostrophe.

    Returns True for words like "can't", "don't", "it's", "they'd",
    "Katherine's". The apostrophe must be internal (not at start/end)
    and both sides must contain at least one letter.
    """
    if "'" not in word:
        return False
    idx = word.index("'")
    left = word[:idx]
    right = word[idx + 1:]
    return len(left) >= 1 and len(right) >= 1 and left[-1].isalpha() and right[0].isalpha()


def split_contraction(word: str) -> tuple[str, str]:
    """Split a contraction at the first apostrophe.

    Returns (left, right) where word = left + "'" + right.
    E.g. "can't" -> ("can", "t"), "Katherine's" -> ("Katherine", "s").
    """
    idx = word.index("'")
    return word[:idx], word[idx + 1:]


def make_synthetic_apostrophe(ink_intensity: int, body_height: int) -> np.ndarray:
    """Create a synthetic apostrophe glyph matching the ink style.

    The apostrophe is a thin curved stroke positioned at the top of
    the character body. It is drawn programmatically rather than
    generated by DiffusionPen, which produces oversized dark blobs
    for punctuation marks.

    Args:
        ink_intensity: Median ink pixel value from surrounding words (0-255,
            lower = darker).
        body_height: Approximate x-height of the surrounding text in pixels.

    Returns:
        Grayscale uint8 image on a white background.
    """
    # Apostrophe dimensions: proportional to body height
    mark_h = max(4, int(body_height * 0.25))
    mark_w = max(2, int(body_height * 0.08))
    # Total image: mark at top third of body height, white padding below
    img_h = body_height
    img_w = mark_w + 4  # 2px padding each side

    img = np.full((img_h, img_w), 255, dtype=np.uint8)

    # Draw a slightly tapered stroke: thicker at top, thinner at bottom
    # Position at top 10-35% of body height
    y_start = max(1, int(body_height * 0.10))
    y_end = y_start + mark_h

    cx = img_w // 2
    for y in range(y_start, min(y_end, img_h)):
        # Taper: full width at top, narrower toward bottom
        progress = (y - y_start) / max(1, mark_h - 1)
        half_w = max(0, int(mark_w * (1.0 - 0.5 * progress) / 2))
        # Gradually lighten toward the bottom for a natural stroke feel
        intensity = int(ink_intensity + (200 - ink_intensity) * progress * 0.6)
        intensity = min(180, max(ink_intensity, intensity))
        for x in range(max(0, cx - half_w), min(img_w, cx + half_w + 1)):
            img[y, x] = intensity

    return img


def stitch_contraction(
    left_img: np.ndarray,
    apostrophe_img: np.ndarray,
    right_img: np.ndarray,
) -> np.ndarray:
    """Stitch a contraction: [left] [apostrophe] [right].

    Aligns all three parts by ink bottom (baseline) and places
    the apostrophe with minimal spacing.
    """
    INK_THRESH = 180

    def _ink_bottom(img):
        ink_rows = np.any(img < INK_THRESH, axis=1)
        if not np.any(ink_rows):
            return 0
        return img.shape[0] - 1 - int(np.argmax(ink_rows[::-1]))

    def _tight_crop_h(img):
        """Tight horizontal crop to ink bounds with 1px padding."""
        col_has_ink = np.any(img < INK_THRESH, axis=0)
        if not np.any(col_has_ink):
            return img
        left = max(0, int(np.argmax(col_has_ink)) - 1)
        right = min(img.shape[1] - 1, len(col_has_ink) - 1 - int(np.argmax(col_has_ink[::-1])) + 1)
        return img[:, left:right + 1]

    # Tight-crop each part horizontally
    left_img = _tight_crop_h(left_img)
    right_img = _tight_crop_h(right_img)

    parts = [left_img, apostrophe_img, right_img]
    bottoms = [_ink_bottom(p) for p in parts]

    # Align by ink bottom
    max_bottom = max(bottoms)
    max_h = max(
        p.shape[0] + (max_bottom - b) for p, b in zip(parts, bottoms)
    )

    aligned = []
    for p, b in zip(parts, bottoms):
        bottom_pad = max_bottom - b
        if bottom_pad > 0:
            pad = np.full((bottom_pad, p.shape[1]), 255, dtype=np.uint8)
            p = np.vstack([p, pad])
        if p.shape[0] < max_h:
            top_pad = np.full((max_h - p.shape[0], p.shape[1]), 255, dtype=np.uint8)
            p = np.vstack([top_pad, p])
        aligned.append(p)

    # Concatenate with 1px gap between apostrophe and neighbors
    gap = np.full((max_h, 1), 255, dtype=np.uint8)
    return np.hstack([aligned[0], gap, aligned[1], gap, aligned[2]])


# --- Syllable splitting ---

def score_split(word: str, pos: int) -> float:
    """Score a split position in a word.

    Considers:
    - Balance: prefer equal-length chunks
    - Consonant penalty: -3 if >= 3 trailing consonants in left chunk
    - Boundary bonus: +2 for CC boundary, +1 for CV boundary
    """
    left, right = word[:pos], word[pos:]
    if len(left) < MIN_CHUNK_CHARS or len(right) < MIN_CHUNK_CHARS:
        return -999

    # Balance score: prefer equal halves
    balance = 1.0 - abs(len(left) - len(right)) / len(word)

    # Consonant cluster penalty
    trailing_consonants = 0
    for c in reversed(left):
        if c in CONSONANTS:
            trailing_consonants += 1
        else:
            break
    consonant_score = CONSONANT_PENALTY if trailing_consonants >= 3 else 0

    # Boundary bonus
    boundary_score = 0
    if pos > 0 and pos < len(word):
        left_char = word[pos - 1]
        right_char = word[pos]
        if left_char in CONSONANTS and right_char in CONSONANTS:
            boundary_score = CC_BOUNDARY_BONUS
        elif left_char in CONSONANTS and right_char in VOWELS:
            boundary_score = CV_BOUNDARY_BONUS

    return balance * 10 + consonant_score + boundary_score


def split_long_word(word: str) -> list[str]:
    """Split a long word into chunks using score-based syllable splitting.

    Each chunk is guaranteed to be >= MIN_CHUNK_CHARS characters.
    """
    if len(word) <= MAX_WORD_LENGTH:
        return [word]

    # Find best split point
    best_pos = None
    best_score = -999
    for pos in range(MIN_CHUNK_CHARS, len(word) - MIN_CHUNK_CHARS + 1):
        s = score_split(word, pos)
        if s > best_score:
            best_score = s
            best_pos = pos

    if best_pos is None:
        # Cannot split while maintaining minimum chunk size
        return [word]

    left = word[:best_pos]
    right = word[best_pos:]

    # Recursively split if chunks are still too long
    chunks = []
    if len(left) > MAX_WORD_LENGTH:
        chunks.extend(split_long_word(left))
    else:
        chunks.append(left)

    if len(right) > MAX_WORD_LENGTH:
        chunks.extend(split_long_word(right))
    else:
        chunks.append(right)

    return chunks


# --- Adaptive canvas width ---

def compute_canvas_width(word_len: int) -> int:
    """Compute canvas width based on word length, up to MAX_CANVAS_WIDTH."""
    if word_len <= 8:
        width = DEFAULT_CANVAS_WIDTH
    else:
        # Scale linearly from 256 to 320 for 8-10 char words
        ratio = min((word_len - 8) / 2, 1.0)
        width = int(DEFAULT_CANVAS_WIDTH + ratio * (MAX_CANVAS_WIDTH - DEFAULT_CANVAS_WIDTH))
    # Round up to multiple of WIDTH_MULTIPLE
    width = ((width + WIDTH_MULTIPLE - 1) // WIDTH_MULTIPLE) * WIDTH_MULTIPLE
    return min(width, MAX_CANVAS_WIDTH)


# --- Postprocessing: 5 gray-box defense layers ---

def adaptive_background_estimate(img: np.ndarray) -> float:
    """Layer 1: 90th-percentile pixel value as background estimate."""
    return float(np.percentile(img, BACKGROUND_PERCENTILE))


def apply_ink_threshold(img: np.ndarray, bg_estimate: float) -> np.ndarray:
    """Create ink mask using adaptive threshold at 70% of background estimate."""
    threshold = bg_estimate * INK_THRESHOLD_RATIO
    ink_mask = img < threshold
    return ink_mask


def body_zone_noise_removal(img: np.ndarray, ink_mask: np.ndarray) -> np.ndarray:
    """Layer 2: Blank columns without sufficient body-zone ink.

    Uses connected-component analysis on strong ink (< 128) to preserve
    columns that are part of the same character as body-zone-valid columns,
    even if those specific columns lack body-zone ink (e.g. crossbar of "T",
    ascenders of "t", "l"). Uses strong ink for connectivity to avoid
    chaining through diffusion noise.
    """
    import cv2

    h, w = img.shape[:2]
    body_top = int(h * BODY_ZONE_TOP)
    body_bottom = int(h * BODY_ZONE_BOTTOM)
    body_zone = ink_mask[body_top:body_bottom, :]

    col_ink_ratio = np.mean(body_zone, axis=0)
    valid_cols = col_ink_ratio >= BODY_ZONE_INK_THRESHOLD

    # Use strong ink (< 128) for connected-component analysis to avoid
    # gray noise chaining into large components
    strong_ink = (img < 128).astype(np.uint8) * 255
    num_labels, labels = cv2.connectedComponents(strong_ink)

    # Find which components touch body-zone-valid columns
    preserved_labels = set()
    for c in range(w):
        if valid_cols[c]:
            col_labels = labels[:, c]
            preserved_labels.update(col_labels[col_labels > 0])

    # Build mask of columns to preserve: body-zone valid OR part of a
    # preserved component
    preserved_cols = valid_cols.copy()
    if preserved_labels:
        labels_arr = np.array(list(preserved_labels))
        for c in range(w):
            if not preserved_cols[c]:
                col_labels = labels[:, c]
                if np.any(np.isin(col_labels, labels_arr)):
                    preserved_cols[c] = True

    result = img.copy()
    for c in range(w):
        if not preserved_cols[c]:
            result[:, c] = 255
    return result


def isolated_cluster_filter(img: np.ndarray, ink_mask: np.ndarray = None) -> np.ndarray:
    """Layer 3: Discard ink clusters separated by large gaps from main cluster.

    Uses a lenient threshold (< 230) for column presence so faint
    inter-letter strokes bridge gaps that the stricter ink_mask misses.
    Clusters are merged transitively: if A is near B and B is near C,
    all three form one group, even if A is far from C. Only truly
    isolated groups (no neighbor within CLUSTER_GAP_PX) are removed.
    """
    h, w = img.shape[:2]

    # Lenient column presence: any pixel below 230 counts, not just
    # the adaptive ink threshold. DiffusionPen generates faint gray
    # (160-200) between letters that should bridge gaps.
    col_has_ink = np.any(img < 230, axis=0)

    # Find connected runs of ink columns
    clusters = []
    start = None
    for c in range(w):
        if col_has_ink[c] and start is None:
            start = c
        elif not col_has_ink[c] and start is not None:
            clusters.append((start, c))
            start = None
    if start is not None:
        clusters.append((start, w))

    if len(clusters) <= 1:
        return img

    # Transitive merge: group clusters where neighbors are within gap threshold
    groups = []  # list of lists of cluster indices
    current_group = [0]
    for i in range(1, len(clusters)):
        prev_end = clusters[i - 1][1]
        curr_start = clusters[i][0]
        gap = curr_start - prev_end
        if gap < CLUSTER_GAP_PX:
            current_group.append(i)
        else:
            groups.append(current_group)
            current_group = [i]
    groups.append(current_group)

    if len(groups) <= 1:
        return img

    # Find the main group (most total ink columns) and preserve any group
    # with significant ink.  Punctuated words ("can't", "it's") produce a
    # gap at the apostrophe; the fragment after it is real content, not noise.
    def group_ink_width(group):
        return sum(clusters[i][1] - clusters[i][0] for i in group)

    total_ink_cols = sum(group_ink_width(g) for g in groups)
    main_group_idx = max(range(len(groups)), key=lambda g: group_ink_width(groups[g]))

    # Minimum fraction of total ink a group must contain to be preserved
    MIN_GROUP_INK_FRACTION = 0.15

    result = img.copy()
    for g_idx, group in enumerate(groups):
        if g_idx == main_group_idx:
            continue
        # Preserve groups with significant ink (not isolated noise)
        if total_ink_cols > 0 and group_ink_width(group) / total_ink_cols >= MIN_GROUP_INK_FRACTION:
            continue
        for ci in group:
            cs, ce = clusters[ci]
            result[:, cs:ce] = 255

    return result


def _word_gray_cleanup(img: np.ndarray) -> np.ndarray:
    """Remove gray fringe pixels not adjacent to strong ink at word level.

    Similar to halo_cleanup but operates on the raw 64x256 word image
    before composition, using a smaller dilation radius suited to the
    smaller pixel scale.
    """
    import cv2

    strong_ink = img < 128
    if not np.any(strong_ink):
        return img

    strong_ink_uint8 = strong_ink.astype(np.uint8) * 255
    # Smaller dilation for word-level (2px vs 4px for halo_cleanup)
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    dilated = cv2.dilate(strong_ink_uint8, kernel)
    near_ink = dilated > 0

    result = img.copy()
    # Only clean mid-to-light gray (160-220), preserving darker gray near ink
    # boundaries that metrics count as ink (< 180)
    gray_pixels = (img >= 160) & (img < 220)
    cleanup_mask = gray_pixels & ~near_ink
    result[cleanup_mask] = 255
    return result


def postprocess_word(img: np.ndarray) -> np.ndarray:
    """Apply all 5 gray-box defense layers to a generated word image.

    Args:
        img: Grayscale uint8 word image from VAE decode.

    Returns:
        Cleaned grayscale uint8 image.
    """
    # Layer 1: Adaptive background estimation
    bg_estimate = adaptive_background_estimate(img)
    ink_mask = apply_ink_threshold(img, bg_estimate)

    # Layer 2: Body-zone noise removal
    img = body_zone_noise_removal(img, ink_mask)

    # Recompute ink mask after layer 2
    ink_mask = apply_ink_threshold(img, bg_estimate)

    # Layer 3: Isolated cluster filtering
    img = isolated_cluster_filter(img, ink_mask)

    # Layer 3b: Word-level gray fringe cleanup
    # Remove gray pixels (128-220) not adjacent to strong ink (< 128)
    img = _word_gray_cleanup(img)

    # Layer 4 (compositor ink-only) is applied during composition in render.py

    # Layer 5 (post-upscale halo cleanup) is applied after upscaling in render.py

    return img


def pad_clipped_descender(img: np.ndarray) -> np.ndarray:
    """Add bottom padding when descender ink is clipped by the canvas edge.

    The 64px generation canvas clips deep descenders (g, j, p, q, y).
    When ink reaches within 2px of the canvas bottom, add white padding
    proportional to the descender depth so the composition stage can
    place the word correctly.
    """
    h = img.shape[0]
    ink_mask = img < 180
    if not np.any(ink_mask):
        return img

    ink_rows = np.any(ink_mask, axis=1)
    last_ink_row = len(ink_rows) - 1 - int(np.argmax(ink_rows[::-1]))
    first_ink_row = int(np.argmax(ink_rows))
    ink_height = last_ink_row - first_ink_row + 1

    # Only pad if ink reaches within 2px of canvas bottom
    if last_ink_row < h - 3:
        return img

    # Padding proportional to ink height: descenders are typically 20-35%
    # of body height. Add 25% of ink height, minimum 6px.
    pad_amount = max(6, int(ink_height * 0.25))
    padding = np.full((pad_amount, img.shape[1]), 255, dtype=np.uint8)
    return np.vstack([img, padding])


def halo_cleanup(img: np.ndarray) -> np.ndarray:
    """Layer 5: Post-upscale halo cleanup.

    Dilate strong-ink mask, blank gray pixels not near dilated ink.
    """
    import cv2

    # Find strong ink pixels
    strong_ink = img < 128
    strong_ink_uint8 = strong_ink.astype(np.uint8) * 255

    # Dilate to create neighborhood mask
    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE, (HALO_DILATE_RADIUS * 2 + 1, HALO_DILATE_RADIUS * 2 + 1)
    )
    dilated = cv2.dilate(strong_ink_uint8, kernel)
    near_ink = dilated > 0

    # Blank gray pixels not near ink
    result = img.copy()
    gray_pixels = (img > 128) & (img < HALO_GRAY_THRESHOLD)
    cleanup_mask = gray_pixels & ~near_ink
    result[cleanup_mask] = 255

    return result


# --- DDIM Sampling ---

def ddim_sample(
    unet,
    vae,
    text_context: dict,
    style_features: torch.Tensor,
    uncond_context: dict | None = None,
    canvas_width: int = DEFAULT_CANVAS_WIDTH,
    num_steps: int = DEFAULT_DDIM_STEPS,
    guidance_scale: float = DEFAULT_GUIDANCE_SCALE,
    device: str = "cuda",
) -> np.ndarray:
    """Run DDIM sampling to generate a single word image.

    Args:
        unet: DiffusionPen UNet model.
        vae: SD 1.5 VAE decoder.
        text_context: Canine-C tokenizer output dict.
        style_features: (5, 1280) raw style features.
        uncond_context: Pre-tokenized unconditional context for CFG.
            If None and guidance_scale != 1.0, CFG is skipped.
        canvas_width: Width of generation canvas.
        num_steps: Number of DDIM steps.
        guidance_scale: CFG guidance scale (1.0 disables CFG).
        device: Torch device.

    Returns:
        Grayscale uint8 numpy array.
    """
    from diffusers import DDIMScheduler

    scheduler = DDIMScheduler(
        beta_start=0.00085,
        beta_end=0.012,
        beta_schedule="scaled_linear",
        clip_sample=False,
    )
    scheduler.set_timesteps(num_steps, device=device)

    latent_h = DEFAULT_CANVAS_HEIGHT // 8
    latent_w = canvas_width // 8

    # Move inputs to device once
    text_ctx = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in text_context.items()}
    style_feat = style_features.to(device)

    # CFG setup
    use_cfg = guidance_scale != 1.0 and uncond_context is not None
    if use_cfg:
        uncond_ctx = {k: v.to(device) if isinstance(v, torch.Tensor) else v for k, v in uncond_context.items()}
        zero_style = torch.zeros_like(style_feat)

    with torch.no_grad():
        # Start from noise
        latents = torch.randn(1, 4, latent_h, latent_w, device=device)

        for t in scheduler.timesteps:
            t_batch = t.unsqueeze(0) if t.dim() == 0 else t

            # Conditional prediction
            noise_pred_cond = unet(
                latents, t_batch, context=text_ctx, y=style_feat,
                style_extractor=style_feat,
            )

            if use_cfg:
                # Unconditional prediction
                noise_pred_uncond = unet(
                    latents, t_batch, context=uncond_ctx, y=zero_style,
                    style_extractor=zero_style,
                )
                noise_pred = noise_pred_uncond + guidance_scale * (noise_pred_cond - noise_pred_uncond)
            else:
                noise_pred = noise_pred_cond

            latents = scheduler.step(noise_pred, t, latents).prev_sample

        # VAE decode
        decoded = vae.decode(latents / VAE_SCALE_FACTOR).sample
        decoded = (decoded / 2 + 0.5).clamp(0, 1)
        img = decoded[0].mean(dim=0).cpu().numpy()

    img = (img * 255).astype(np.uint8)
    return img


def generate_word(
    word: str,
    unet,
    vae,
    tokenizer,
    style_features: torch.Tensor,
    uncond_context: dict | None = None,
    num_steps: int = DEFAULT_DDIM_STEPS,
    guidance_scale: float = DEFAULT_GUIDANCE_SCALE,
    num_candidates: int = DEFAULT_NUM_CANDIDATES,
    device: str = "cuda",
    style_reference_imgs: list[np.ndarray] | None = None,
    reference_stroke_width: float = 0.0,
) -> np.ndarray:
    """Generate a single word image with best-of-N candidate selection.

    Long words (>10 chars) are split, generated as chunks, and stitched.

    Candidates with OCR accuracy below 0.4 are rejected; up to 2 extra
    retries are attempted to find a readable result.

    Args:
        uncond_context: Pre-tokenized unconditional context for CFG.
            Build once with tokenizer(" ", ...) and reuse across all words.
        style_reference_imgs: Raw grayscale style word images for tiebreaking.
            When two candidates have quality scores within 0.05, the one
            with higher style similarity wins.
        reference_stroke_width: Target stroke width from style images.
            When > 0, candidate scoring penalizes stroke width deviation.
    """
    import logging

    from reforge.quality.score import quality_score

    log = logging.getLogger("reforge.generator")

    # Contraction path: bypass DiffusionPen's poor apostrophe rendering
    # by generating left and right parts separately with a synthetic mark.
    if is_contraction(word):
        left_text, right_text = split_contraction(word)
        log.debug("contraction split: %s -> %s + ' + %s", word, left_text, right_text)
        return _generate_contraction(
            left_text, right_text, word,
            unet, vae, tokenizer, style_features,
            uncond_context=uncond_context,
            num_steps=num_steps,
            guidance_scale=guidance_scale,
            num_candidates=num_candidates,
            device=device,
            style_reference_imgs=style_reference_imgs,
            reference_stroke_width=reference_stroke_width,
        )

    chunks = split_long_word(word)

    # OCR function: needed for candidate scoring (num_candidates > 1)
    # and post-selection rejection loop.
    ocr_fn = _get_ocr_fn() if num_candidates > 1 else None

    def _generate_chunk(chunk_text: str) -> tuple[np.ndarray, float]:
        """Generate a word chunk with best-of-N selection.

        Returns (image, ocr_accuracy). ocr_accuracy is -1.0 when OCR
        scoring was not performed (num_candidates == 1).
        """
        canvas_width = compute_canvas_width(len(chunk_text))
        text_ctx = tokenizer(chunk_text, return_tensors="pt", padding="max_length", max_length=16)

        candidates = []
        for _ in range(num_candidates):
            img = ddim_sample(
                unet, vae, text_ctx, style_features,
                uncond_context=uncond_context,
                canvas_width=canvas_width,
                num_steps=num_steps,
                guidance_scale=guidance_scale,
                device=device,
            )
            img = postprocess_word(img)
            img = pad_clipped_descender(img)
            img_score = quality_score(
                img,
                reference_stroke_width=reference_stroke_width,
                word_len=len(chunk_text) if num_candidates > 1 else 0,
            )

            # A1: OCR-aware scoring when multiple candidates
            if ocr_fn is not None:
                ocr_acc = ocr_fn(img, chunk_text)
                combined = (1 - OCR_SELECTION_WEIGHT) * img_score + OCR_SELECTION_WEIGHT * ocr_acc
                candidates.append((img, img_score, ocr_acc, combined))
                log.debug(
                    "candidate %s: quality=%.3f ocr=%.3f combined=%.3f",
                    chunk_text, img_score, ocr_acc, combined,
                )
            else:
                candidates.append((img, img_score, -1.0, img_score))

        # Select best candidate by combined score
        best_combined = max(c[3] for c in candidates)

        # Style similarity tiebreaker: among candidates within 0.05
        # of the best combined score, prefer higher style similarity
        if style_reference_imgs is not None and len(candidates) > 1:
            from reforge.evaluate.visual import compute_style_similarity
            tied = [c for c in candidates if c[3] >= best_combined - 0.05]
            if len(tied) > 1:
                winner = max(
                    tied,
                    key=lambda c: compute_style_similarity(c[0], style_reference_imgs),
                )
                log.debug(
                    "selected %s: quality=%.3f ocr=%.3f combined=%.3f (style tiebreak)",
                    chunk_text, winner[1], winner[2], winner[3],
                )
                return winner[0], winner[2]

        winner = max(candidates, key=lambda c: c[3])
        log.debug(
            "selected %s: quality=%.3f ocr=%.3f combined=%.3f",
            chunk_text, winner[1], winner[2], winner[3],
        )
        return winner[0], winner[2]

    if len(chunks) == 1:
        best, known_ocr_acc = _generate_chunk(word)

        # OCR-based rejection: retry if accuracy is too low.
        # Threshold 0.4 catches borderline cases (e.g. "an" at 0.33) that
        # 0.3 missed. Retries trigger on ~10% of words; cost is acceptable.
        # A3: reuse known OCR accuracy from candidate scoring to avoid
        # redundant TrOCR call on the selected candidate.
        rejection_ocr_fn = _get_ocr_fn()
        if rejection_ocr_fn is not None:
            ocr_threshold = 0.4
            max_retries = 2
            # If OCR-aware scoring already computed accuracy, reuse it
            best_acc = known_ocr_acc if known_ocr_acc >= 0 else 0.0
            first_check_done = known_ocr_acc >= 0

            for attempt in range(max_retries):
                if not first_check_done or attempt > 0:
                    acc = rejection_ocr_fn(best, word)
                    best_acc = max(best_acc, acc)
                else:
                    acc = known_ocr_acc
                    best_acc = max(best_acc, acc)

                if acc >= ocr_threshold:
                    break

                # Retry with fresh generation
                retry, retry_known_acc = _generate_chunk(word)
                if retry_known_acc >= 0:
                    retry_acc = retry_known_acc
                else:
                    retry_acc = rejection_ocr_fn(retry, word)
                best_acc = max(best_acc, retry_acc)
                if retry_acc > acc:
                    best = retry
                    if retry_acc >= ocr_threshold:
                        break
            else:
                # Exhausted retries without reaching threshold
                _record_hard_word_candidate(word, best_acc)

        return best

    # Multi-chunk: generate each, normalize heights, baseline-align, stitch
    chunk_images = [_generate_chunk(chunk)[0] for chunk in chunks]
    return stitch_chunks(chunk_images)


def _get_ocr_fn():
    """Return ocr_accuracy function if available, else None."""
    try:
        from reforge.evaluate.ocr import ocr_accuracy
        return ocr_accuracy
    except ImportError:
        return None


def _record_hard_word_candidate(word: str, best_acc: float) -> None:
    """Record a word that exhausted OCR retries as a hard word candidate."""
    try:
        from reforge.data.words import add_candidate
        add_candidate(word, source="ocr_rejection", ocr_accuracy=best_acc)
    except Exception:
        pass  # Non-critical; do not interrupt generation


def _generate_contraction(
    left_text: str,
    right_text: str,
    full_word: str,
    unet,
    vae,
    tokenizer,
    style_features,
    uncond_context=None,
    num_steps=DEFAULT_DDIM_STEPS,
    guidance_scale=DEFAULT_GUIDANCE_SCALE,
    num_candidates=DEFAULT_NUM_CANDIDATES,
    device="cuda",
    style_reference_imgs=None,
    reference_stroke_width=0.0,
) -> np.ndarray:
    """Generate a contraction by producing parts separately with a synthetic apostrophe.

    Generates left_text and right_text as independent words, creates a
    synthetic apostrophe mark derived from the ink properties of the
    generated parts, and stitches all three together. This bypasses
    DiffusionPen's poor apostrophe rendering.
    """
    import logging

    from reforge.quality.ink_metrics import compute_x_height
    from reforge.quality.score import quality_score

    log = logging.getLogger("reforge.generator")

    ocr_fn = _get_ocr_fn() if num_candidates > 1 else None

    def _gen_part(text):
        canvas_width = compute_canvas_width(len(text))
        text_ctx = tokenizer(text, return_tensors="pt", padding="max_length", max_length=16)
        best_img = None
        best_score = -999
        for _ in range(num_candidates):
            img = ddim_sample(
                unet, vae, text_ctx, style_features,
                uncond_context=uncond_context,
                canvas_width=canvas_width,
                num_steps=num_steps,
                guidance_scale=guidance_scale,
                device=device,
            )
            img = postprocess_word(img)
            img = pad_clipped_descender(img)
            score = quality_score(
                img,
                reference_stroke_width=reference_stroke_width,
                word_len=len(text) if num_candidates > 1 else 0,
            )
            if ocr_fn is not None:
                from reforge.config import OCR_SELECTION_WEIGHT
                ocr_acc = ocr_fn(img, text)
                combined = (1 - OCR_SELECTION_WEIGHT) * score + OCR_SELECTION_WEIGHT * ocr_acc
            else:
                combined = score
            if combined > best_score:
                best_score = combined
                best_img = img
        return best_img

    left_img = _gen_part(left_text)
    right_img = _gen_part(right_text)

    # Derive apostrophe properties from the generated left part
    ink_pixels = left_img[left_img < 180]
    ink_intensity = int(np.median(ink_pixels)) if len(ink_pixels) > 0 else 60
    body_h = compute_x_height(left_img)

    apostrophe_img = make_synthetic_apostrophe(ink_intensity, body_h)

    result = stitch_contraction(left_img, apostrophe_img, right_img)
    log.debug(
        "contraction stitched: %s (%dx%d) + ' + %s (%dx%d) -> %dx%d",
        left_text, left_img.shape[1], left_img.shape[0],
        right_text, right_img.shape[1], right_img.shape[0],
        result.shape[1], result.shape[0],
    )
    return result


def stitch_chunks(chunks: list[np.ndarray]) -> np.ndarray:
    """Stitch word chunks with ink-height alignment and overlap blending.

    - Measure each chunk's ink region (top/bottom ink rows)
    - Scale chunks so ink heights match (median ink height)
    - Align by ink bottom (baseline), not image bottom
    - Overlap blending at stitch boundaries
    """
    import cv2

    from reforge.quality.ink_metrics import compute_x_height

    if len(chunks) == 1:
        return chunks[0]

    # Horizontal tight-crop: strip leading/trailing whitespace columns
    # from each chunk to eliminate the gap between stitched pieces
    INK_THRESH = 180
    cropped = []
    for chunk in chunks:
        col_has_ink = np.any(chunk < INK_THRESH, axis=0)
        if np.any(col_has_ink):
            first_col = np.argmax(col_has_ink)
            last_col = len(col_has_ink) - 1 - np.argmax(col_has_ink[::-1])
            # Keep 2px margin on each side for overlap blending
            first_col = max(0, first_col - 2)
            last_col = min(chunk.shape[1] - 1, last_col + 2)
            chunk = chunk[:, first_col:last_col + 1]
        cropped.append(chunk)
    chunks = cropped

    # Measure x-height (body zone, excluding ascenders/descenders)
    # for normalization, plus ink bounds for baseline alignment
    x_heights = []
    ink_bottoms = []  # distance from image bottom to last ink row
    for chunk in chunks:
        x_h = compute_x_height(chunk)
        x_heights.append(x_h)
        # Find last ink row (baseline position)
        ink_rows = np.any(chunk < INK_THRESH, axis=1)
        if np.any(ink_rows):
            last_ink = len(ink_rows) - 1 - np.argmax(ink_rows[::-1])
            ink_bottoms.append(chunk.shape[0] - 1 - last_ink)
        else:
            ink_bottoms.append(0)

    # Scale each chunk so x-height matches the median x-height.
    # X-height normalization matches the letter body size, not the total
    # ink extent, preventing "under" (tall) and "standing" (short body)
    # from looking mismatched when stitched.
    median_x_h = int(np.median(x_heights))
    if median_x_h < 4:
        median_x_h = max(x_heights)  # fallback for very small ink

    normalized = []
    for i, chunk in enumerate(chunks):
        if x_heights[i] > 0 and x_heights[i] != median_x_h:
            scale = median_x_h / x_heights[i]
            new_h = max(1, int(chunk.shape[0] * scale))
            new_w = max(1, int(chunk.shape[1] * scale))
            chunk = cv2.resize(chunk, (new_w, new_h), interpolation=cv2.INTER_AREA)
        normalized.append(chunk)

    # Re-measure ink bottoms after scaling (scaling shifts pixel positions)
    scaled_ink_bottoms = []
    for chunk in normalized:
        ink_rows = np.any(chunk < INK_THRESH, axis=1)
        if np.any(ink_rows):
            last_ink = len(ink_rows) - 1 - np.argmax(ink_rows[::-1])
            scaled_ink_bottoms.append(chunk.shape[0] - 1 - last_ink)
        else:
            scaled_ink_bottoms.append(0)

    # Align by ink bottom (baseline): pad so all chunks have the same
    # distance from their last ink row to the image bottom
    max_ink_bottom = max(scaled_ink_bottoms)
    max_h = max(c.shape[0] + (max_ink_bottom - scaled_ink_bottoms[i])
                for i, c in enumerate(normalized))

    padded = []
    for i, chunk in enumerate(normalized):
        # Pad at bottom to align baselines
        bottom_pad = max_ink_bottom - scaled_ink_bottoms[i]
        if bottom_pad > 0:
            pad_bottom = np.full((bottom_pad, chunk.shape[1]), 255, dtype=np.uint8)
            chunk = np.vstack([chunk, pad_bottom])
        # Pad at top to equalize total height
        if chunk.shape[0] < max_h:
            pad_top = np.full((max_h - chunk.shape[0], chunk.shape[1]), 255, dtype=np.uint8)
            chunk = np.vstack([pad_top, chunk])
        padded.append(chunk)

    # Stitch with overlap blending
    total_width = sum(c.shape[1] for c in padded) - STITCH_OVERLAP_PX * (len(padded) - 1)
    result = np.full((max_h, total_width), 255, dtype=np.uint8)

    x = 0
    for i, chunk in enumerate(padded):
        if i == 0:
            result[:, x : x + chunk.shape[1]] = chunk
            x += chunk.shape[1] - STITCH_OVERLAP_PX
        else:
            # Blend overlap region
            overlap_start = x
            overlap_end = x + STITCH_OVERLAP_PX

            for ox in range(STITCH_OVERLAP_PX):
                alpha = ox / STITCH_OVERLAP_PX  # 0->1 from left to right
                col_idx = overlap_start + ox
                if col_idx < result.shape[1]:
                    prev_col = result[:, col_idx].astype(np.float32)
                    new_col = chunk[:, ox].astype(np.float32)
                    result[:, col_idx] = ((1 - alpha) * prev_col + alpha * new_col).astype(np.uint8)

            # Copy rest of chunk
            rest_start = STITCH_OVERLAP_PX
            dest_start = overlap_end
            rest_width = chunk.shape[1] - rest_start
            if dest_start + rest_width <= result.shape[1]:
                result[:, dest_start : dest_start + rest_width] = chunk[:, rest_start:]

            x = dest_start + rest_width - STITCH_OVERLAP_PX

    return result
